language: php
php:
  - 7.1
  - 7.2
  - master

env:
  - dependencies=lowest
  - dependencies=highest

matrix:
  allow_failures:
    - php: master
      env: dependencies=lowest
    - php: master
      env: dependencies=highest

before_script:
  - composer self-update
  - if [ "$dependencies" = "lowest"  ]; then composer update --no-interaction --prefer-lowest; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi;

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit
    - if [ "$dependencies" = "highest" ]; then php vendor/bin/phpstan analyze --level=4 src tests; fi;

after_script:
    - php vendor/bin/php-coveralls -v
