language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

env:
  - dependencies=lowest
  - dependencies=highest

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

stages:
    - Code style & static analysis
    - test

jobs:
    include:
        - stage: Code style & static analysis
          name: PHP CS Fixer
          script: composer phpcs
        - script: composer phpstan
          name: PHPStan

install:
    - if [ "$dependencies" = "lowest"  ]; then composer update --no-interaction --prefer-lowest --prefer-dist; fi;
    - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --prefer-dist; fi;

script:
    - composer tests

after_success:
    - php vendor/bin/php-coveralls -v
